theme: jekyll-theme-dinky
github:
    hw_url: https://github.com/marcin-sielski/hazyair/wiki
    api_url: https://github.com/marcin-sielski/hazyair/wiki/API
    npm_url: https://www.npmjs.com/package/hazyair
    owner_name: Marcin Sielski
